### ISSUE TITLE
settings_credentials.py.skel - No such file or directory

### ISSUE THREAD

**Issue by bobanmak** [nbproject/nbproject#278]
I'm trying to install NB on my Debian server. After using the command `make django` i am getting this Error message: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "apps/nbsite/settings.py", line 16, in <module>
    shutil.copy2("%s/%s.skel" % (thisdir, FN_CREDENTIALS), "%s/%s" % (thisdir, FN_CREDENTIALS))
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/root/nbproject/apps/nbsite/settings_credentials.py.skel' 
```

So basicly, the make file creates every file but not the `settings_credentials.py.skel` . Any ideas?

Thanks in advanced,
Bob

**Comment by kesiena115** [comment]
The file may have been missing at that point. It's now present in that folder if you clone the current repo.
